theme: minima
title: Something somthing anime
author: CommodoreEvac
email: commodoreevac@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yabba dabba do.

# social links
twitter_username: No have Twitter # DO NOT include the @ character, or else the build will fail!
github_username:  CommodoreEvac # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
